services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_its_stage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/dump-its.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./Database/migrations:/docker-entrypoint-migrations:ro
      - ./scripts/docker/apply-migrations.sh:/docker-entrypoint-initdb.d/02-apply-migrations.sh:ro

volumes:
  postgres_data: