services:
  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_its_stage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./PowerBI/dump-its_gestionale_tirocini-202603282222.sql:/bootstrap/dump.sql:ro

volumes:
  postgres_data: