version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: its-postgres
    restart: always
    environment:
      POSTGRES_USER: its_user
      POSTGRES_PASSWORD: its_password
      POSTGRES_DB: its_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: