# Nome dell'applicazione
spring.application.name=gestionale

# ── Database ──────────────────────────────────────
# localhost perché Spring Boot ora gira sul tuo PC,
# fuori da Docker. Quando lo dockerizzeremo,
# cambierà in "postgres" (nome del servizio Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_its_stage
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ───────────────────────────────
# update = crea/aggiorna le tabelle automaticamente
spring.jpa.hibernate.ddl-auto=update
# Mostra le query SQL nel log (utile per imparare)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disabilita Spring Security temporaneamente per i test
# DA RIABILITARE prima di andare in produzione!
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


# ── Server ────────────────────────────────────────
server.port=8080