spring.application.name=gestionale

# 🔗 Database
spring.datasource.url=jdbc:postgresql://localhost:5432/its_db
spring.datasource.username=its_user
spring.datasource.password=its_password

# 🧠 JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect